steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'endpoint-slide4vr-pptx2png', '--image', 'gcr.io/$PROJECT_ID/kuda-proxy', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']